image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node 19

build_script:
  - yarn
  - yarn build
  - yarn prepare-release
  - yarn package appx
  - yarn prepare-release
  - yarn package linux

test_script:
  - yarn lint
  - yarn test

artifacts:
  - path: 'build\clean\build\*.appx'
