name: Update Website

on: [release, workflow_dispatch]

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run readme
      - uses: stefanzweifel/git-auto-commit-action@v5
